url: "https://localvegasrestaurants.com"

collections:  # process the _data folder
  components:
    output: false
  places:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "places"
    values:
      layout: "place"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - "*.conf"
  - "*.json"
  - "*.lock"
  - "*.py"
  - "*.toml"
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
